### ISSUE TITLE
A possible problem with the second skin-based authentication idea

### ISSUE THREAD

**Issue by Sea-Kerman** [Aizistral-Studios/Trustless-Authentication#1]
Certain other mods (like Entity Texture Features) use the whitespace in skin images, so some collaboration might be needed so the key doesn't mess up skin features.

**Comment by Aizistral** [comment]
That problem is to be solved within the bounds of specific project and implementation, not general concept which readme outlines. But to give you some perspective - if we use elliptic curves, 256-bit public key can be encoded in as little as 8 pixels. It shouldn't be much trouble to find a spot that is not used by any mods for them, and/or just give user an ability to adjust where they are positioned.
